### ISSUE TITLE
add on does not appear in the add on list.

### ISSUE THREAD

**Issue by nexxio** [doakey3/VSE_Transform_Tools#3]

**Comment by doakey3** [comment]
This was an issue a few days ago that I thoight I fixed. Are you using the most recent version? Try deleting the old version and installing the new one.

**Comment by nexxio** [comment]
is the recent version. I deleted it and installed again and still does not show up.

**Comment by doakey3** [comment]
You're right. For whatever reason, if you rename the .zip file to "VSE_Transform_Tools.zip" instead of "VSE_Transform_Tools-1.1.5" seems to solve it. I will figure out why, but in the mean time you could probably install it this way.

**Comment by nexxio** [comment]
ohhh, I was having that issue with another addon because the file name start with numbers, if I delete the numbers from the name it works. so this means no numbers in addon files.
*I renamed the file to VSE_Transform_Tools.zip and worked!
thanks for the help.

**Comment by doakey3** [comment]
I have added new links to each release that should install correctly in Blender. Thanks for making me aware of this issue. I probably would not have found it without help.
